vim-checkbox-movements: implemented
tanhauhau/Inquirer.sh pull request #11
Opened 2017-08-09 23:24 UTC by tennysontbardwell

added a new function to interpret ascii keys in the checkbox file, if
the key is j or k it is remapped to the up/down function

2017-08-09 23:25 UTC, tennysontbardwell commented
Really wanted this for myself, hope you consider merging it for others!

2017-08-10 02:58 UTC, kahkhang commented
Thanks for your contributions @tennysontbardwell ! Do you mind running `python build.py` to generate the consolidated bash scripts before we merge this in?

2017-08-10 03:09 UTC, kahkhang requested changes
Do you mind addressing these comments as well? Thanks!

2017-08-10 03:09 UTC, kahkhang commented on dev/checkbox_input.sh
> +_null() {
Could you remove this and use the `on_default` function already in `inquirer_common.sh`? Thanks!

2017-08-10 03:09 UTC, kahkhang commented on dev/checkbox_input.sh
> +  on_keypress on_checkbox_input_up on_checkbox_input_down on_checkbox_input_space on_checkbox_input_enter _null _null on_checkbox_input_ascii
Change `_null` to `on_default`

2017-08-10 03:09 UTC, kahkhang commented on dist/checkbox_input.sh
> +_null() {
Please remove this too

2017-08-10 03:09 UTC, kahkhang commented on dist/checkbox_input.sh
> +  on_keypress on_checkbox_input_up on_checkbox_input_down on_checkbox_input_space on_checkbox_input_enter _null _null on_checkbox_input_ascii
And change `_null` to `on_default`

2017-08-14 16:55 UTC, tennysontbardwell commented
Good catch @kahkhang ! I cleaned it up.

Btw, I did run `python build.py` before the first commit, it generated `dist/`. Please tell me if I didn't do it correctly!

2017-08-14 22:39 UTC, kahkhang commented
🎉 Thanks so much @tennysontbardwell ! LGTM

2017-08-14 22:39 UTC, merged